/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author AnnaDC
 */
public class JFrameAuxiliarLlibres extends javax.swing.JFrame {
    
    
     // declaració de variables:
    // a l'acadèmia:
    final String IP = "192.168.1.18";
    final String PORT = "3306";
    final String DBASE = "ad_biblioteca";
    final String USER = "adiez";
    final String PASSWORD = "";
    // a casa:
    /*final String IP = "localhost";
    final String PORT = "8889";
    final String DBASE = "ad_biblioteca";
    final String USER = "root";
    final String PASSWORD = "root";*/
    
    //DefaultTableModel model1 = new DefaultTableModel();
    databases db1 = new databases();
    retorn_query rq = null;
    
    

    /**
     * Creates new form JFrameAuxiliarLlibres
     */
    public JFrameAuxiliarLlibres() {
        initComponents();
        db1 = new databases();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Taula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valors");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/icons/add.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 80));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/icons/close.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 80));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BiblioGest: Manteniment");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/icons/edit.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setPreferredSize(new java.awt.Dimension(80, 80));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // Botó d'afegir items
        
        int seleccio = jComboBox1.getSelectedIndex();
        String taula = "";
        String camp = "";
        String codi = "";
        
        //bi04_nom, bi05_nom_editorial, bi06_nom_genere, bi07_nom_tema, bi08_nom_idioma
        
        switch (seleccio) {
            case 0:
                taula = "bi04_autors";
                camp = "bi04_nom";
                codi = "bi04_id";
                break;
            case 1:
                taula = "bi05_editorials";
                camp = "bi05_nom_editorial";
                codi = "bi05_id";
                break;
            case 2:
                taula = "bi06_generes";
                camp = "bi06_nom_genere";
                codi = "bi06_id";
                break;
            case 3:
                taula = "bi07_temes";
                camp = "bi07_nom_tema";
                codi = "bi07_id";
                break;
            case 4:
                taula = "bi08_idiomes";
                camp = "bi08_nom_idioma";
                codi = "bi08_id";
                break;
        }
        
        String insertItem = "insert into " + taula + " ("+ camp +") values ('" +
                jTextField1.getText() + "')";
        String nouCodi = "select max(" + codi + ") from " + taula;
        String codiId = "";
        
        try {
            db1.modifyDB(IP, PORT, DBASE, USER, PASSWORD, insertItem);
            rq = db1.queryDB(IP, PORT, DBASE, USER, PASSWORD, nouCodi);
            rq.getRs().next();
            codiId = rq.getRs().getString(1);
            jComboBox2.addItem(new ComboItem(codiId, jTextField1.getText()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:.
        
        // Botó de treure items
        
        //obtenim el codi a eliminar
        ComboItem cItem = (ComboItem)jComboBox2.getSelectedItem();
        String codi = cItem.getId();
        
        // trobem la taula
        int seleccio = jComboBox1.getSelectedIndex();
        String taula = "";
        String camp = "";
        switch (seleccio) {
            case 0:
                taula = "bi04_autors";
                camp = "bi04_id";
                break;
            case 1:
                taula = "bi05_editorials";
                camp = "bi05_id";
                break;
            case 2:
                taula = "bi06_generes";
                camp = "bi06_id";
                break;
            case 3:
                taula = "bi07_temes";
                camp = "bi07_id";
                break;
            case 4:
                taula = "bi08_idiomes";
                camp = "bi08_id";
                break;
        }
        
        String esborraElement = "delete from " + taula + " where " + camp 
                + "=" + codi;
        
        try {
            db1.modifyDB(IP, PORT, DBASE, USER, PASSWORD, esborraElement);
            jComboBox2.removeItemAt(jComboBox2.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No es pot esborrar aquest "
                    + "registre ja que està associat a algun llibre");
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        // ComboBox de taules
        
        int seleccio = jComboBox1.getSelectedIndex();
        String query = "";
        jComboBox2.removeAllItems();
        
        switch (seleccio) {
            case 0:
                query = "select * from bi04_autors";
                break;
            case 1:
                query = "select * from bi05_editorials";
                break;
            case 2:
                query = "select * from bi06_generes";
                break;
            case 3:
                query = "select * from bi07_temes";
                break;
            case 4:
                query = "select * from bi08_idiomes";
                break;
            default:    
                query = "select * from bi08_idiomes WHERE 1 = 0";
        }
        
        try {
            rq = db1.queryDB(IP, PORT, DBASE, USER, PASSWORD, query);

            while (rq.getRs().next()) {
                String codi = rq.getRs().getString(1);
                String nom = rq.getRs().getString(2);

                jComboBox2.addItem(new ComboItem(codi, nom));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        // ComboBox d'items
        
        jTextField1.setText("");
        
        //if (jComboBox2.isValid()) { és millor així:
        if (jComboBox2.getItemCount() != 0) {
            ComboItem cItem = (ComboItem) jComboBox2.getSelectedItem();
            jTextField1.setText(cItem.toString());
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        jComboBox1.addItem("Autor");
        jComboBox1.addItem("Editorial");
        jComboBox1.addItem("Gènere");
        jComboBox1.addItem("Tema");
        jComboBox1.addItem("Idioma");
        
        jComboBox1.setSelectedIndex(-1);
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        // Botó d'editar items
        
        int seleccio = jComboBox1.getSelectedIndex();
        ComboItem cItem = (ComboItem)jComboBox2.getSelectedItem();
        String taula = "";
        String camp = "";
        String codi = "";
        
        switch (seleccio) {
            case 0:
                taula = "bi04_autors";
                camp = "bi04_nom";
                codi = "bi04_id";
                break;
            case 1:
                taula = "bi05_editorials";
                camp = "bi05_nom_editorial";
                codi = "bi05_id";
                break;
            case 2:
                taula = "bi06_generes";
                camp = "bi06_nom_genere";
                codi = "bi06_id";
                break;
            case 3:
                taula = "bi07_temes";
                camp = "bi07_nom_tema";
                codi = "bi07_id";
                break;
            case 4:
                taula = "bi08_idiomes";
                camp = "bi08_nom_idioma";
                codi = "bi08_id";
                break;
        }
        
        
        // update bi08_idiomes set bi08_nom_idioma='xinès' where bi08_id=102;
        String modificaItem ="update " + taula + " set " + camp + "='" 
                + jTextField1.getText() + "' where " + codi + "=" + cItem.getId();
                
        String codiId = cItem.getId();
        String nom=jTextField1.getText();
        
        
        try {
            db1.modifyDB(IP, PORT, DBASE, USER, PASSWORD, modificaItem);
            jComboBox2.removeItemAt(jComboBox2.getSelectedIndex());
            jComboBox2.addItem(new ComboItem(codiId, nom));
            jComboBox2.setSelectedIndex(0);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /*private void ompleCombo(String query, JComboBox combobox) {

        databases db1 = new databases();
        retorn_query rq = null;

        try {

            rq = db1.queryDB(IP, PORT, DBASE,
                    USER, PASSWORD, query);
            while (rq.getRs().next()) {
                String codiProv = rq.getRs().getString(1);
                String nomProv = rq.getRs().getString(2);
                ComboItem cItem = new ComboItem(codiProv, nomProv);
                combobox.addItem(cItem);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } finally {
            try {
                db1.desconnecta(rq.getConexio());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }

    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAuxiliarLlibres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAuxiliarLlibres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAuxiliarLlibres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAuxiliarLlibres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAuxiliarLlibres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
